name = "Underdog5"
git_repository = "https://github.com/TwelveFacedJanus/Underdog"
dependencies = ["cmake", "make"]

[formula]
install_cmds = ["cd underdog5 && cmake .. -B Build && cd Build && make && ./Underdog"]
